sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t anirudhaagnihotri/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anirudhagnihotri/docker-react npm run test
